#!/bin/bash

function init() (
    sudo apt update && sudo apt install --auto-remove -y lcov python3-venv python3-pip python3-dev python3-setuptools 
	python3 -m venv venv
	. venv/bin/activate && pip install .
)

function test() (
	. venv/bin/activate && pytest --cov-report term-missing --cov-report lcov:./tests/lcov/cov.info --cov=mm tests
	genhtml ./tests/lcov/cov.info -o ./tests/lcov/html
)

function pkg() (
    # replace the verion in the pyproject.toml with the current git tag
    sed -Ei 's|^(version[[:blank:]]*=[[:blank:]]*).*$|echo \1\\"`git describe --tags --abbrev=0`\\"|e' pyproject.toml
	python3 -m pip install --upgrade build
	python3 -m build    
)