# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        make init 
    - name: Test with pytest
      run: |
        make test
    - name: upload code coverage
      uses: actions/upload-artifact@v4
      with:
        name: code coverage
        path: ./tests/lcov/html/*
        if-no-files-found: error
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: create wheel
      run: |
        env
        make init pkg 
        chmod 777 dist/*
    - name: upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: python wheel
        path: dist
        if-no-files-found: error     


